export { default as DonateSection } from './DonateSection/DonateSection'
export { default as Footer } from './Footer/Footer'
export { default as NavigationBar } from './NavigationBar/NavigationBar'
export { default as YourDonationsSection } from './YourDonationsSection/YourDonationsSection'
export { default as MainContent } from './MainContent/MainContent'
